name=LoraA39C
version=0.1.0
author=SuXYIO <suxymc@163.com>
maintainer=SuXYIO <suxymc@163.com>
sentence=Arduino library for A39C-T400A22D1a Lora wireless module.
paragraph=
category=Communication
url=https://codeberg.org/uwaeng/lora_a39c_arduino
architectures=*
includes=LoraA39C.h
