name=LoraA39C
version=0.1.0
author=SuXYIO <suxymc@163.com>
maintainer=SuXYIO <suxymc@163.com>
sentence=Arduino library for A39C-T400A22D1a Lora wireless module.
paragraph=Note that this library has not implemented full functionalities of the module yet, but it should be enough for simple cases.
category=Communication
url=https://codeberg.org/uwaeng/lora_a39c_arduino
architectures=*
includes=LoraA39C.h
