name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: codeberg-tiny-lazy
    steps:
      - uses: actions/checkout@v7
      - uses: https://github.com/arduino/arduino-lint-action@v3
        with:
          compliance: strict
          token: ${{ secrets.GH_TOKEN }}
